# Generated by Django 3.1.1 on 2020-09-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Renters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Contact_number', models.IntegerField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('area', models.CharField(max_length=100)),
            ],
        ),
    ]
