# Generated by Django 3.1.1 on 2020-09-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renters',
            name='Contact_number',
            field=models.IntegerField(),
        ),
    ]
