# Generated by Django 3.1.1 on 2020-10-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Renters', '0002_auto_20200930_0325'),
        ('Renters', '0002_auto_20200930_0328'),
    ]

    operations = [
    ]
