# Generated by Django 3.1.1 on 2020-10-07 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Renters', '0003_merge_20201006_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renters',
            name='Contact_number',
        ),
        migrations.RemoveField(
            model_name='renters',
            name='area',
        ),
        migrations.RemoveField(
            model_name='renters',
            name='email',
        ),
        migrations.RemoveField(
            model_name='renters',
            name='name',
        ),
        migrations.AddField(
            model_name='renters',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
