# Generated by Django 3.1.1 on 2020-10-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renters', '0005_auto_20201009_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/thh.jpg', upload_to='images/profile'),
        ),
    ]
