# Generated by Django 3.1.1 on 2020-10-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Renters', '0006_auto_20201009_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renter',
            name='profile_picture',
        ),
    ]
