# Generated by Django 3.1.1 on 2020-09-21 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0004_house_landlord'),
        ('Landlord', '0002_auto_20200921_0044'),
        ('Advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='House.house'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='landlord',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Landlord.landlord'),
        ),
    ]
