# Generated by Django 3.1.1 on 2020-09-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='Contact_number',
            field=models.IntegerField(max_length=25),
        ),
    ]
