# Generated by Django 3.1.1 on 2020-09-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0004_remove_landlord_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='Contact_number',
            field=models.IntegerField(),
        ),
    ]
