# Generated by Django 3.1.1 on 2020-10-07 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Landlord', '0007_landlord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='Contact_number',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='email',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='name',
        ),
        migrations.AlterField(
            model_name='landlord',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
