# Generated by Django 3.1.1 on 2020-10-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0008_auto_20201007_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='Contact_number',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='email',
            field=models.EmailField(default=1, max_length=100, null=True),
        ),
    ]
