# Generated by Django 3.1.1 on 2020-10-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0009_auto_20201008_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='Contact_number',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='email',
        ),
    ]
