# Generated by Django 3.1.1 on 2020-09-23 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('House', '0002_auto_20200923_1529'),
        ('Landlord', '0002_auto_20200921_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='House.house')),
                ('landlord', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Landlord.landlord')),
            ],
        ),
    ]
