# Generated by Django 3.1.1 on 2020-09-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisment', '0002_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='images/thh.jpg', upload_to='images/Houes'),
        ),
    ]
