# Generated by Django 3.1.1 on 2020-09-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisment', '0004_auto_20200929_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image2',
            field=models.ImageField(default='images/th.jpg', upload_to='images/Advertisement'),
        ),
    ]
