# Generated by Django 3.1.1 on 2020-09-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(max_length=10)),
                ('size_in_sqfeet', models.IntegerField(max_length=10)),
                ('rent', models.IntegerField(max_length=25)),
            ],
        ),
    ]
