# Generated by Django 3.1.1 on 2020-09-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('house_no', models.IntegerField(max_length=10)),
                ('road_no', models.IntegerField(max_length=10)),
                ('area', models.CharField(max_length=25)),
            ],
        ),
    ]
