# Generated by Django 3.1.1 on 2020-09-23 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0002_auto_20200921_0044'),
        ('House', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('house_no', models.IntegerField(max_length=10)),
                ('road_no', models.IntegerField(max_length=10)),
                ('area', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='landlord',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Landlord.landlord'),
        ),
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='House.address'),
        ),
    ]
