# Generated by Django 3.1.1 on 2020-09-21 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='House.address'),
        ),
    ]
