# Generated by Django 3.1.1 on 2020-09-21 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0002_auto_20200921_0044'),
        ('House', '0003_house_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='landlord',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Landlord.landlord'),
        ),
    ]
