# Generated by Django 3.1.1 on 2020-10-09 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('House', '0007_merge_20201006_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='landlord',
        ),
        migrations.AddField(
            model_name='house',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
