# Generated by Django 3.1.1 on 2020-10-09 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20201008_2144'),
        ('House', '0008_auto_20201009_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='user',
        ),
        migrations.AddField(
            model_name='house',
            name='landlord',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.profile'),
        ),
    ]
