# Generated by Django 3.1.1 on 2020-10-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0009_auto_20201009_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='landlord',
            new_name='profile',
        ),
    ]
