# Generated by Django 3.1.1 on 2020-10-09 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0010_auto_20201008_2100'),
        ('House', '0010_auto_20201009_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='profile',
        ),
        migrations.AddField(
            model_name='house',
            name='landlord',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Landlord.landlord'),
        ),
    ]
